apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
namespace: default
resources:
- ../../base
patches:
- path: patch.yaml
images:
- name: eliasdb/webshop-api
  newName: eliasdb/webshop-api
  newTag: v2.1
