apiVersion: v1
kind: Service
metadata:
  name: clara-api
  labels:
    app: clara-api
spec:
  type: ClusterIP
  selector:
    app: clara-api
  ports:
    - name: http
      port: 9101
      targetPort: 9101
