apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
namespace: default
resources:
- ../../base
patches:
- path: patch-env.yaml
  # Pin to an immutable prod tag
images:
- name: eliasdb/edb
  newName: eliasdb/edb
  newTag: v2.1
