apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
namespace: default

resources:
- ../../base

# Pin an explicit prod tag here
images:
- name: eliasdb/edb-admin
  newName: eliasdb/edb-admin
  newTag: v2.1

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: production
  target:
    kind: Deployment
    name: admin-client
