apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
namespace: default

resources:
- ../../base

patches:
- path: patch-deployment.yaml

images:
- name: eliasdb/clara-api
  newName: eliasdb/clara-api
  newTag: v2.1
