apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshop-api
spec:
  template:
    spec:
      containers:
        - name: webshop-api
          env:
            - name: APP_ENV
              value: 'staging'
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: webshop-api-secret
                  key: APP_KEY
            - name: APP_DEBUG
              value: 'false'
            - name: APP_URL
              value: 'https://api.staging.eliasdebock.com'

            - name: DB_CONNECTION
              value: 'pgsql'
            - name: DB_HOST
              value: 'postgres-service-staging'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-staging
                  key: POSTGRES_USER
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-staging
                  key: POSTGRES_DB
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-staging
                  key: POSTGRES_PASSWORD

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret-staging
                  key: OPENAI_API_KEY

            - name: MEILISEARCH_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch-secret-staging
                  key: MEILI_MASTER_KEY

            - name: STRIPE_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-staging
                  key: STRIPE_PUBLIC
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-staging
                  key: STRIPE_SECRET
            - name: KEYCLOAK_JWKS_URL
              value: 'https://app.staging.eliasdebock.com/keycloak/realms/EDB-PROD/protocol/openid-connect/certs'
