apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-staging
  namespace: auth
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx-argo
  rules:
    - host: app.staging.eliasdebock.com
      http:
        paths:
          - path: /keycloak(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak-staging
                port:
                  number: 8080
