apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
namespace: default
resources:
  - ../../base
images:
  - name: eliasdb/clara-client
    newName: eliasdb/clara-client
    newTag: v2.1
