apiVersion: apps/v1
kind: Deployment
metadata:
  name: clara-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: clara-api
          # Image Updater will rewrite this tag automatically
          image: eliasdb/clara-api:pr-0-staging
          envFrom:
            - secretRef:
                name: clara-api-db
            - configMapRef:
                name: clara-api-config
          env:
            - name: NODE_ENV
              value: 'staging'
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret-staging
                  key: OPENAI_API_KEY
            - name: HUBSPOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hubspot-secret-staging
                  key: HUBSPOT_TOKEN
            - name: HUBSPOT_BASE
              valueFrom:
                secretKeyRef:
                  name: hubspot-secret-staging
                  key: HUBSPOT_BASE
